
export interface commercialProposal  {
  code: string | null,
  company: string | null,
  customer: string | null,
  customerReference: string | null,
  servicioConcept: string | null,
  typeOfService: string | null,
  currency: string | null,
  stateP: string | null,
  baseAmount: number | null,
  totalAmount: number | null,
  version: number | null,
  dateVersion: string | null,
  proposalId:number | null,
  folder: string | null,
  wayToPay: string | null,
  wayToPayDays: string | null,
  creatorUser:  string |null,
}
